version: '3'
services:
  db:
    image: postgres:10.1
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432"

  api:
    build: .
    environment:
      DATABASE_HOST: db
      RAILS_ENV: production
      SECRET_KEY_BASE: $SECRET_KEY_BASE
    env_file:
      - .env
    volumes:
      - tmp-data:/app/tmp
      - public-data:/app/public
      - /var/run/docker.sock:/var/run/docker.sock
      # Docker for Mac
      - /usr/local/bin/docker:/usr/bin/docker
    ports:
      - "3000"
    depends_on:
      - db
    links:
      - db

  web:
    build: nginx/
    ports:
      - "80:80"
    volumes:
      - tmp-data:/app/tmp
      - public-data:/app/public
    depends_on:
      - api
        # links:
        # - db

volumes:
  data: {}
  tmp-data:
  public-data:
